[package]
name = "shared"
version = "0.1.0"
edition = "2021"
rust-version = "1.66"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
name = "shared"

[features]
typegen = ["crux_core/typegen"]

[dependencies]
crux_core = { version = "0.6" }
crux_macros = { version = "0.3" }
serde = { workspace = true, features = ["derive"] }
lazy_static = "1.4.0"
uniffi = "0.23.0"
wasm-bindgen = "0.2.86"

[target.uniffi-bindgen.dependencies]
uniffi = { version = "0.23.0", features = ["cli"] }

[build-dependencies]
uniffi = { version = "0.23.0", features = ["build"] }
